# Generated by Django 4.2 on 2023-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="nom de l'etudiant")),
                ('age', models.IntegerField(null=1, verbose_name="age de l'etudiant")),
                ('phone', models.CharField(max_length=50, verbose_name="phone de l'etudiant")),
            ],
        ),
    ]
