# Generated by Django 4.2 on 2023-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='nom de Username')),
                ('password', models.CharField(max_length=50, verbose_name='password de Username')),
                ('email', models.EmailField(max_length=50, verbose_name='email de User')),
            ],
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
