# Generated by Django 4.2 on 2023-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_alter_logininfo_email_alter_logininfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
